name: C Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang
    
    - name: Build and Run Tests
      run: |
        cd Tests
        make
        ./AllTest.out > test_results.txt
        if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: Tests/test_results.txt