name: c-unit-testing-example

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: compile 
      run: cd Tests && make all

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Run Unit tests.
        run: cd Tests && make all && ../AllTest.out